/* eslint-disable */

export const GROUP = [
    'Group 1',
    'Group 2',
    'Group 3',
    'Group 4',
    'Group 5',
    'Group 6',
    'Group 7',
    'Group 8',
    'Group 9',
    'Group 10'
  ]

export const EMPLOYEE_DATA = [
    {
        username: 'jluckwell0',
        firstName: 'Jakie',
        lastName: 'Luckwell',
        email: 'jluckwell0@gizmodo.com',
        birthDate: '1928-12-09',
        basicSalary: 6857696,
        status: 'Inactive',
        group: 'group 1',
        description: '1960-11-04',
    },
    {
        username: 'dtuddall1',
        firstName: 'Devonne',
        lastName: 'Tuddall',
        email: 'dtuddall1@fastcompany.com',
        birthDate: '2007-08-24',
        basicSalary: 2694012,
        status: 'Inactive',
        group: 'group 2',
        description: '2008-09-25',
    },
    {
        username: 'ewaplington2',
        firstName: 'Elden',
        lastName: 'Waplington',
        email: 'ewaplington2@cbc.ca',
        birthDate: '1937-12-25',
        basicSalary: 6409157,
        status: 'Inactive',
        group: 'group 2',
        description: '1943-12-08',
    },
    {
        username: 'kmusk3',
        firstName: 'Kris',
        lastName: 'Musk',
        email: 'kmusk3@mayoclinic.com',
        birthDate: '1921-12-29',
        basicSalary: 4367083,
        status: 'Inactive',
        group: 'group 4',
        description: '1956-10-12',
    },
    {
        username: 'cbirdall4',
        firstName: 'Celka',
        lastName: 'Birdall',
        email: 'cbirdall4@bizjournals.com',
        birthDate: '1967-03-05',
        basicSalary: 9430292,
        status: 'Inactive',
        group: 'group 4',
        description: '2020-12-09',
    },
    {
        username: 'ppaver5',
        firstName: 'Patten',
        lastName: 'Paver',
        email: 'ppaver5@mit.edu',
        birthDate: '1908-06-16',
        basicSalary: 1952457,
        status: 'Active',
        group: 'group 3',
        description: '1915-07-11',
    },
    {
        username: 'nellesworth6',
        firstName: 'Nessie',
        lastName: 'Ellesworth',
        email: 'nellesworth6@dailymotion.com',
        birthDate: '1986-10-11',
        basicSalary: 9104278,
        status: 'Inactive',
        group: 'group 2',
        description: '1974-03-28',
    },
    {
        username: 'zphysic7',
        firstName: 'Zorana',
        lastName: 'Physic',
        email: 'zphysic7@t.co',
        birthDate: '1902-04-04',
        basicSalary: 3822345,
        status: 'Active',
        group: 'group 3',
        description: '1908-12-24',
    },
    {
        username: 'dlethbridge8',
        firstName: 'Di',
        lastName: 'Lethbridge',
        email: 'dlethbridge8@eepurl.com',
        birthDate: '1970-02-05',
        basicSalary: 6325790,
        status: 'Active',
        group: 'group 5',
        description: '1981-07-19',
    },
    {
        username: 'jpenley9',
        firstName: 'Javier',
        lastName: 'Penley',
        email: 'jpenley9@vk.com',
        birthDate: '2016-04-17',
        basicSalary: 6118964,
        status: 'Active',
        group: 'group 4',
        description: '1966-09-16',
    },
    {
        username: 'gbarcka',
        firstName: 'Gina',
        lastName: 'Barck',
        email: 'gbarcka@hexun.com',
        birthDate: '2017-07-30',
        basicSalary: 3796177,
        status: 'Active',
        group: 'group 2',
        description: '1903-01-12',
    },
    {
        username: 'acossingtonb',
        firstName: 'Alessandro',
        lastName: 'Cossington',
        email: 'acossingtonb@dailymotion.com',
        birthDate: '2005-09-20',
        basicSalary: 6957503,
        status: 'Inactive',
        group: 'group 5',
        description: '1940-12-19',
    },
    {
        username: 'aslopierc',
        firstName: 'Alexio',
        lastName: 'Slopier',
        email: 'aslopierc@gizmodo.com',
        birthDate: '1957-01-03',
        basicSalary: 2156350,
        status: 'Active',
        group: 'group 2',
        description: '1956-09-30',
    },
    {
        username: 'nstolworthyd',
        firstName: 'Nesta',
        lastName: 'Stolworthy',
        email: 'nstolworthyd@prweb.com',
        birthDate: '1941-04-03',
        basicSalary: 1554761,
        status: 'Active',
        group: 'group 3',
        description: '1941-10-02',
    },
    {
        username: 'atoplise',
        firstName: 'Allina',
        lastName: 'Toplis',
        email: 'atoplise@house.gov',
        birthDate: '1973-01-18',
        basicSalary: 5482101,
        status: 'Active',
        group: 'group 4',
        description: '1976-10-26',
    },
    {
        username: 'bclareyf',
        firstName: 'Breanne',
        lastName: 'Clarey',
        email: 'bclareyf@unc.edu',
        birthDate: '1927-03-16',
        basicSalary: 8972616,
        status: 'Active',
        group: 'group 1',
        description: '1968-11-22',
    },
    {
        username: 'jskeathg',
        firstName: 'Julissa',
        lastName: 'Skeath',
        email: 'jskeathg@oakley.com',
        birthDate: '1925-11-18',
        basicSalary: 2575701,
        status: 'Active',
        group: 'group 1',
        description: '1971-01-17',
    },
    {
        username: 'mflaniganh',
        firstName: 'Marcelo',
        lastName: 'Flanigan',
        email: 'mflaniganh@opera.com',
        birthDate: '2014-10-26',
        basicSalary: 516826,
        status: 'Active',
        group: 'group 3',
        description: '1987-05-22',
    },
    {
        username: 'mblakeleyi',
        firstName: 'Mira',
        lastName: 'Blakeley',
        email: 'mblakeleyi@google.ca',
        birthDate: '1966-11-05',
        basicSalary: 6090731,
        status: 'Active',
        group: 'group 5',
        description: '1978-07-08',
    },
    {
        username: 'lmcclochj',
        firstName: 'Leola',
        lastName: 'McCloch',
        email: 'lmcclochj@admin.ch',
        birthDate: '1956-12-22',
        basicSalary: 4114991,
        status: 'Active',
        group: 'group 2',
        description: '2001-03-20',
    },
    {
        username: 'cjacqueminotk',
        firstName: 'Correy',
        lastName: 'Jacqueminot',
        email: 'cjacqueminotk@liveinternet.ru',
        birthDate: '1999-08-19',
        basicSalary: 296568,
        status: 'Active',
        group: 'group 4',
        description: '1922-02-28',
    },
    {
        username: 'lowbridgel',
        firstName: 'Leighton',
        lastName: 'Owbridge',
        email: 'lowbridgel@yandex.ru',
        birthDate: '1921-08-21',
        basicSalary: 39345,
        status: 'Active',
        group: 'group 2',
        description: '1979-05-11',
    },
    {
        username: 'jguddm',
        firstName: 'Jason',
        lastName: 'Gudd',
        email: 'jguddm@purevolume.com',
        birthDate: '1977-08-11',
        basicSalary: 9568329,
        status: 'Inactive',
        group: 'group 2',
        description: '1995-05-02',
    },
    {
        username: 'roagn',
        firstName: 'Rouvin',
        lastName: 'Oag',
        email: 'roagn@chicagotribune.com',
        birthDate: '1999-10-21',
        basicSalary: 8531638,
        status: 'Inactive',
        group: 'group 1',
        description: '1990-05-30',
    },
    {
        username: 'eiveyo',
        firstName: 'Eugenie',
        lastName: 'Ivey',
        email: 'eiveyo@phpbb.com',
        birthDate: '1937-12-03',
        basicSalary: 8322898,
        status: 'Active',
        group: 'group 4',
        description: '1999-02-25',
    },
    {
        username: 'lrapellip',
        firstName: 'Lamond',
        lastName: 'Rapelli',
        email: 'lrapellip@prlog.org',
        birthDate: '1987-03-06',
        basicSalary: 4695847,
        status: 'Active',
        group: 'group 3',
        description: '1956-10-09',
    },
    {
        username: 'dshellibeerq',
        firstName: 'Donal',
        lastName: 'Shellibeer',
        email: 'dshellibeerq@4shared.com',
        birthDate: '1976-12-21',
        basicSalary: 9976060,
        status: 'Active',
        group: 'group 2',
        description: '1958-05-02',
    },
    {
        username: 'sskoylesr',
        firstName: 'Siusan',
        lastName: 'Skoyles',
        email: 'sskoylesr@uiuc.edu',
        birthDate: '1974-08-22',
        basicSalary: 8393391,
        status: 'Active',
        group: 'group 2',
        description: '1922-05-12',
    },
    {
        username: 'bswetts',
        firstName: 'Boigie',
        lastName: 'Swett',
        email: 'bswetts@gravatar.com',
        birthDate: '2004-01-08',
        basicSalary: 6124805,
        status: 'Inactive',
        group: 'group 2',
        description: '1973-09-07',
    },
    {
        username: 'cwiltont',
        firstName: 'Codi',
        lastName: 'Wilton',
        email: 'cwiltont@constantcontact.com',
        birthDate: '1935-07-03',
        basicSalary: 1051579,
        status: 'Inactive',
        group: 'group 4',
        description: '2011-01-11',
    },
    {
        username: 'jmcshirrieu',
        firstName: 'Joete',
        lastName: 'McShirrie',
        email: 'jmcshirrieu@statcounter.com',
        birthDate: '1919-12-08',
        basicSalary: 5084328,
        status: 'Active',
        group: 'group 3',
        description: '1904-11-18',
    },
    {
        username: 'nbeachv',
        firstName: 'Nikola',
        lastName: 'Beach',
        email: 'nbeachv@icio.us',
        birthDate: '1976-04-14',
        basicSalary: 157173,
        status: 'Active',
        group: 'group 1',
        description: '1981-08-21',
    },
    {
        username: 'gwhebellw',
        firstName: 'Germayne',
        lastName: 'Whebell',
        email: 'gwhebellw@google.co.uk',
        birthDate: '2007-03-10',
        basicSalary: 7515281,
        status: 'Inactive',
        group: 'group 3',
        description: '1985-03-02',
    },
    {
        username: 'mgrishmanovx',
        firstName: 'Missy',
        lastName: 'Grishmanov',
        email: 'mgrishmanovx@icq.com',
        birthDate: '1936-08-05',
        basicSalary: 252526,
        status: 'Active',
        group: 'group 5',
        description: '1997-03-29',
    },
    {
        username: 'khaddocky',
        firstName: 'Klement',
        lastName: 'Haddock',
        email: 'khaddocky@topsy.com',
        birthDate: '1908-06-08',
        basicSalary: 4697774,
        status: 'Inactive',
        group: 'group 5',
        description: '1993-12-25',
    },
    {
        username: 'jwarbeyz',
        firstName: 'Juliet',
        lastName: 'Warbey',
        email: 'jwarbeyz@uiuc.edu',
        birthDate: '1903-11-29',
        basicSalary: 4273982,
        status: 'Inactive',
        group: 'group 5',
        description: '1920-01-13',
    },
    {
        username: 'jscoular10',
        firstName: 'Jud',
        lastName: 'Scoular',
        email: 'jscoular10@cargocollective.com',
        birthDate: '1906-10-31',
        basicSalary: 1729064,
        status: 'Active',
        group: 'group 3',
        description: '1927-01-19',
    },
    {
        username: 'tzanelli11',
        firstName: 'Tito',
        lastName: 'Zanelli',
        email: 'tzanelli11@digg.com',
        birthDate: '1908-07-26',
        basicSalary: 7945289,
        status: 'Inactive',
        group: 'group 2',
        description: '1937-07-25',
    },
    {
        username: 'aeastman12',
        firstName: 'Ashley',
        lastName: 'Eastman',
        email: 'aeastman12@amazon.co.uk',
        birthDate: '1962-07-02',
        basicSalary: 2981343,
        status: 'Active',
        group: 'group 3',
        description: '1985-01-04',
    },
    {
        username: 'dskelhorne13',
        firstName: 'Duke',
        lastName: 'Skelhorne',
        email: 'dskelhorne13@businessweek.com',
        birthDate: '1927-10-25',
        basicSalary: 5077717,
        status: 'Active',
        group: 'group 3',
        description: '1921-09-29',
    },
    {
        username: 'gcorker14',
        firstName: 'Gustave',
        lastName: 'Corker',
        email: 'gcorker14@miitbeian.gov.cn',
        birthDate: '1967-09-12',
        basicSalary: 452034,
        status: 'Active',
        group: 'group 5',
        description: '1951-07-26',
    },
    {
        username: 'istigger15',
        firstName: 'Ilse',
        lastName: 'Stigger',
        email: 'istigger15@twitter.com',
        birthDate: '2018-12-12',
        basicSalary: 6800258,
        status: 'Active',
        group: 'group 1',
        description: '2022-02-03',
    },
    {
        username: 'vstokes16',
        firstName: 'Vlad',
        lastName: 'Stokes',
        email: 'vstokes16@is.gd',
        birthDate: '1907-09-17',
        basicSalary: 1746148,
        status: 'Inactive',
        group: 'group 3',
        description: '2010-08-18',
    },
    {
        username: 'kjonuzi17',
        firstName: 'Kip',
        lastName: 'Jonuzi',
        email: 'kjonuzi17@amazon.co.jp',
        birthDate: '1957-05-13',
        basicSalary: 5442108,
        status: 'Inactive',
        group: 'group 3',
        description: '1982-08-03',
    },
    {
        username: 'rwarden18',
        firstName: 'Royal',
        lastName: 'Warden',
        email: 'rwarden18@fc2.com',
        birthDate: '1960-02-27',
        basicSalary: 5279508,
        status: 'Inactive',
        group: 'group 4',
        description: '1971-10-03',
    },
    {
        username: 'ldyball19',
        firstName: 'Linell',
        lastName: 'Dyball',
        email: 'ldyball19@si.edu',
        birthDate: '1938-08-20',
        basicSalary: 3618888,
        status: 'Inactive',
        group: 'group 2',
        description: '2006-05-09',
    },
    {
        username: 'gcroysdale1a',
        firstName: 'Gayel',
        lastName: 'Croysdale',
        email: 'gcroysdale1a@alibaba.com',
        birthDate: '1997-07-01',
        basicSalary: 9036523,
        status: 'Inactive',
        group: 'group 2',
        description: '1964-01-04',
    },
    {
        username: 'lstratten1b',
        firstName: 'Lemmy',
        lastName: 'Stratten',
        email: 'lstratten1b@hao123.com',
        birthDate: '1988-07-24',
        basicSalary: 6011943,
        status: 'Inactive',
        group: 'group 2',
        description: '1954-11-02',
    },
    {
        username: 'spilbury1c',
        firstName: 'Steffi',
        lastName: 'Pilbury',
        email: 'spilbury1c@wikia.com',
        birthDate: '1906-07-21',
        basicSalary: 8113596,
        status: 'Inactive',
        group: 'group 2',
        description: '1935-01-14',
    },
    {
        username: 'wjizhaki1d',
        firstName: 'Wylma',
        lastName: 'Jizhaki',
        email: 'wjizhaki1d@google.ru',
        birthDate: '1958-04-24',
        basicSalary: 8488510,
        status: 'Inactive',
        group: 'group 2',
        description: '1954-06-08',
    },
    {
        username: 'kboffey1e',
        firstName: 'Katusha',
        lastName: 'Boffey',
        email: 'kboffey1e@stumbleupon.com',
        birthDate: '1920-01-03',
        basicSalary: 5683960,
        status: 'Active',
        group: 'group 3',
        description: '1974-02-11',
    },
    {
        username: 'fbrient1f',
        firstName: 'Felice',
        lastName: 'Brient',
        email: 'fbrient1f@usnews.com',
        birthDate: '1997-03-13',
        basicSalary: 5311230,
        status: 'Inactive',
        group: 'group 4',
        description: '1902-09-09',
    },
    {
        username: 'smcduffy1g',
        firstName: 'Sonia',
        lastName: 'McDuffy',
        email: 'smcduffy1g@nhs.uk',
        birthDate: '1917-07-04',
        basicSalary: 2688890,
        status: 'Inactive',
        group: 'group 1',
        description: '2012-10-30',
    },
    {
        username: 'vbavester1h',
        firstName: 'Vonnie',
        lastName: 'Bavester',
        email: 'vbavester1h@xinhuanet.com',
        birthDate: '1940-04-08',
        basicSalary: 1033586,
        status: 'Active',
        group: 'group 1',
        description: '1902-03-20',
    },
    {
        username: 'dbantham1i',
        firstName: 'Dorothy',
        lastName: 'Bantham',
        email: 'dbantham1i@jimdo.com',
        birthDate: '1965-04-25',
        basicSalary: 4768484,
        status: 'Inactive',
        group: 'group 2',
        description: '1983-08-12',
    },
    {
        username: 'larderne1j',
        firstName: 'Lincoln',
        lastName: 'Arderne',
        email: 'larderne1j@behance.net',
        birthDate: '2020-07-15',
        basicSalary: 4285906,
        status: 'Active',
        group: 'group 2',
        description: '1940-02-02',
    },
    {
        username: 'bfaveryear1k',
        firstName: 'Britteny',
        lastName: 'Faveryear',
        email: 'bfaveryear1k@sohu.com',
        birthDate: '1917-04-09',
        basicSalary: 7061045,
        status: 'Active',
        group: 'group 3',
        description: '2022-12-24',
    },
    {
        username: 'kgaler1l',
        firstName: 'King',
        lastName: 'Galer',
        email: 'kgaler1l@slashdot.org',
        birthDate: '1938-09-29',
        basicSalary: 9923230,
        status: 'Active',
        group: 'group 3',
        description: '2010-06-08',
    },
    {
        username: 'timos1m',
        firstName: 'Tomi',
        lastName: 'Imos',
        email: 'timos1m@washingtonpost.com',
        birthDate: '1906-12-13',
        basicSalary: 1845053,
        status: 'Active',
        group: 'group 5',
        description: '1906-06-19',
    },
    {
        username: 'zvoyce1n',
        firstName: 'Zorina',
        lastName: 'Voyce',
        email: 'zvoyce1n@intel.com',
        birthDate: '1967-03-24',
        basicSalary: 3017680,
        status: 'Active',
        group: 'group 3',
        description: '1959-12-15',
    },
    {
        username: 'dgamble1o',
        firstName: 'Delphine',
        lastName: 'Gamble',
        email: 'dgamble1o@constantcontact.com',
        birthDate: '2004-09-27',
        basicSalary: 1549570,
        status: 'Active',
        group: 'group 2',
        description: '1992-06-05',
    },
    {
        username: 'dpike1p',
        firstName: 'Demeter',
        lastName: 'Pike',
        email: 'dpike1p@edublogs.org',
        birthDate: '1975-08-13',
        basicSalary: 777959,
        status: 'Inactive',
        group: 'group 2',
        description: '1992-06-02',
    },
    {
        username: 'malfonsetto1q',
        firstName: 'Marieann',
        lastName: 'Alfonsetto',
        email: 'malfonsetto1q@angelfire.com',
        birthDate: '1969-08-28',
        basicSalary: 1415255,
        status: 'Active',
        group: 'group 2',
        description: '1985-08-07',
    },
    {
        username: 'kgidley1r',
        firstName: 'Kaleb',
        lastName: 'Gidley',
        email: 'kgidley1r@163.com',
        birthDate: '1987-06-19',
        basicSalary: 8180646,
        status: 'Active',
        group: 'group 3',
        description: '1902-03-15',
    },
    {
        username: 'dbrisset1s',
        firstName: 'Dionne',
        lastName: 'Brisset',
        email: 'dbrisset1s@examiner.com',
        birthDate: '1984-09-25',
        basicSalary: 1710138,
        status: 'Active',
        group: 'group 2',
        description: '1915-04-30',
    },
    {
        username: 'mstarte1t',
        firstName: 'Melodie',
        lastName: 'Starte',
        email: 'mstarte1t@weebly.com',
        birthDate: '1945-04-21',
        basicSalary: 5316039,
        status: 'Inactive',
        group: 'group 5',
        description: '1990-05-12',
    },
    {
        username: 'wweinmann1u',
        firstName: 'Wit',
        lastName: 'Weinmann',
        email: 'wweinmann1u@ebay.co.uk',
        birthDate: '1906-06-18',
        basicSalary: 3162786,
        status: 'Active',
        group: 'group 2',
        description: '2020-08-16',
    },
    {
        username: 'cboylin1v',
        firstName: 'Ches',
        lastName: 'Boylin',
        email: 'cboylin1v@merriam-webster.com',
        birthDate: '2013-11-13',
        basicSalary: 7306533,
        status: 'Active',
        group: 'group 2',
        description: '1983-10-01',
    },
    {
        username: 'cmanwaring1w',
        firstName: 'Chancey',
        lastName: 'Manwaring',
        email: 'cmanwaring1w@paginegialle.it',
        birthDate: '1935-12-06',
        basicSalary: 7947984,
        status: 'Inactive',
        group: 'group 3',
        description: '1913-03-28',
    },
    {
        username: 'bpasque1x',
        firstName: 'Beitris',
        lastName: 'Pasque',
        email: 'bpasque1x@jigsy.com',
        birthDate: '1978-06-19',
        basicSalary: 9177303,
        status: 'Active',
        group: 'group 2',
        description: '1914-03-28',
    },
    {
        username: 'moxberry1y',
        firstName: 'Mellisent',
        lastName: 'Oxberry',
        email: 'moxberry1y@tripod.com',
        birthDate: '1938-06-18',
        basicSalary: 1371372,
        status: 'Active',
        group: 'group 4',
        description: '2013-02-03',
    },
    {
        username: 'dchurchin1z',
        firstName: 'Doroteya',
        lastName: 'Churchin',
        email: 'dchurchin1z@pbs.org',
        birthDate: '1937-04-23',
        basicSalary: 1361652,
        status: 'Inactive',
        group: 'group 2',
        description: '2022-12-06',
    },
    {
        username: 'ghay20',
        firstName: 'Gerry',
        lastName: 'Hay',
        email: 'ghay20@vinaora.com',
        birthDate: '1990-08-28',
        basicSalary: 4697086,
        status: 'Active',
        group: 'group 2',
        description: '1982-06-16',
    },
    {
        username: 'rcolson21',
        firstName: 'Rochell',
        lastName: 'Colson',
        email: 'rcolson21@sogou.com',
        birthDate: '1954-09-18',
        basicSalary: 7046982,
        status: 'Inactive',
        group: 'group 1',
        description: '1974-02-16',
    },
    {
        username: 'jcrank22',
        firstName: 'Jodee',
        lastName: 'Crank',
        email: 'jcrank22@ftc.gov',
        birthDate: '1961-02-26',
        basicSalary: 1010431,
        status: 'Active',
        group: 'group 1',
        description: '1991-09-15',
    },
    {
        username: 'agrundwater23',
        firstName: 'Aeriel',
        lastName: 'Grundwater',
        email: 'agrundwater23@ftc.gov',
        birthDate: '2010-10-05',
        basicSalary: 1070693,
        status: 'Active',
        group: 'group 2',
        description: '1955-01-01',
    },
    {
        username: 'jbalshen24',
        firstName: 'Jany',
        lastName: 'Balshen',
        email: 'jbalshen24@digg.com',
        birthDate: '2022-06-09',
        basicSalary: 4119447,
        status: 'Inactive',
        group: 'group 3',
        description: '1981-12-12',
    },
    {
        username: 'cspittle25',
        firstName: 'Carie',
        lastName: 'Spittle',
        email: 'cspittle25@yahoo.com',
        birthDate: '1995-01-22',
        basicSalary: 3702446,
        status: 'Inactive',
        group: 'group 1',
        description: '1999-09-12',
    },
    {
        username: 'sclayill26',
        firstName: 'Sofie',
        lastName: 'Clayill',
        email: 'sclayill26@smh.com.au',
        birthDate: '1945-02-02',
        basicSalary: 1059940,
        status: 'Inactive',
        group: 'group 2',
        description: '2022-06-06',
    },
    {
        username: 'vmaccaughey27',
        firstName: 'Vachel',
        lastName: 'MacCaughey',
        email: 'vmaccaughey27@omniture.com',
        birthDate: '1926-02-07',
        basicSalary: 5610602,
        status: 'Active',
        group: 'group 3',
        description: '1955-09-06',
    },
    {
        username: 'ayouel28',
        firstName: 'Arlana',
        lastName: 'Youel',
        email: 'ayouel28@nhs.uk',
        birthDate: '1958-07-14',
        basicSalary: 3456202,
        status: 'Active',
        group: 'group 1',
        description: '1937-11-12',
    },
    {
        username: 'mpegden29',
        firstName: 'Margy',
        lastName: 'Pegden',
        email: 'mpegden29@globo.com',
        birthDate: '1955-05-14',
        basicSalary: 8598172,
        status: 'Inactive',
        group: 'group 4',
        description: '1927-08-25',
    },
    {
        username: 'hlead2a',
        firstName: 'Harper',
        lastName: 'Lead',
        email: 'hlead2a@exblog.jp',
        birthDate: '1918-09-16',
        basicSalary: 1260859,
        status: 'Inactive',
        group: 'group 5',
        description: '2006-05-06',
    },
    {
        username: 'vbrandli2b',
        firstName: 'Vanni',
        lastName: 'Brandli',
        email: 'vbrandli2b@wikia.com',
        birthDate: '1909-05-27',
        basicSalary: 1785348,
        status: 'Inactive',
        group: 'group 1',
        description: '1926-11-24',
    },
    {
        username: 'ftayspell2c',
        firstName: 'Franchot',
        lastName: 'Tayspell',
        email: 'ftayspell2c@bizjournals.com',
        birthDate: '1919-04-29',
        basicSalary: 4986963,
        status: 'Active',
        group: 'group 5',
        description: '1989-07-31',
    },
    {
        username: 'aduggan2d',
        firstName: 'Anita',
        lastName: 'Duggan',
        email: 'aduggan2d@goodreads.com',
        birthDate: '1975-08-28',
        basicSalary: 603234,
        status: 'Inactive',
        group: 'group 5',
        description: '1966-02-12',
    },
    {
        username: 'gglashby2e',
        firstName: 'Godwin',
        lastName: 'Glashby',
        email: 'gglashby2e@ow.ly',
        birthDate: '1925-11-26',
        basicSalary: 8310244,
        status: 'Active',
        group: 'group 1',
        description: '1975-11-11',
    },
    {
        username: 'jkingsly2f',
        firstName: 'Janna',
        lastName: 'Kingsly',
        email: 'jkingsly2f@state.tx.us',
        birthDate: '1979-09-06',
        basicSalary: 2848253,
        status: 'Active',
        group: 'group 3',
        description: '1950-10-18',
    },
    {
        username: 'caspland2g',
        firstName: 'Chrotoem',
        lastName: 'Aspland',
        email: 'caspland2g@moonfruit.com',
        birthDate: '1937-09-06',
        basicSalary: 3410886,
        status: 'Active',
        group: 'group 2',
        description: '1981-08-23',
    },
    {
        username: 'gstinchcombe2h',
        firstName: 'Grete',
        lastName: 'Stinchcombe',
        email: 'gstinchcombe2h@marketwatch.com',
        birthDate: '1929-09-28',
        basicSalary: 9736705,
        status: 'Inactive',
        group: 'group 2',
        description: '1985-05-09',
    },
    {
        username: 'wfairhurst2i',
        firstName: 'Wally',
        lastName: 'Fairhurst',
        email: 'wfairhurst2i@census.gov',
        birthDate: '1991-05-13',
        basicSalary: 7248828,
        status: 'Active',
        group: 'group 4',
        description: '1929-06-02',
    },
    {
        username: 'pskamal2j',
        firstName: 'Patrica',
        lastName: 'Skamal',
        email: 'pskamal2j@example.com',
        birthDate: '1922-06-05',
        basicSalary: 6964129,
        status: 'Inactive',
        group: 'group 2',
        description: '1944-06-27',
    },
    {
        username: 'bphalp2k',
        firstName: 'Benoite',
        lastName: 'Phalp',
        email: 'bphalp2k@sphinn.com',
        birthDate: '1963-08-19',
        basicSalary: 9766072,
        status: 'Active',
        group: 'group 1',
        description: '1977-08-29',
    },
    {
        username: 'bimlock2l',
        firstName: 'Brigida',
        lastName: 'Imlock',
        email: 'bimlock2l@linkedin.com',
        birthDate: '2018-11-06',
        basicSalary: 6787104,
        status: 'Inactive',
        group: 'group 3',
        description: '1904-11-17',
    },
    {
        username: 'rphlippsen2m',
        firstName: 'Ripley',
        lastName: 'Phlippsen',
        email: 'rphlippsen2m@amazon.co.jp',
        birthDate: '1993-04-26',
        basicSalary: 3197486,
        status: 'Inactive',
        group: 'group 3',
        description: '1941-01-11',
    },
    {
        username: 'cgarvie2n',
        firstName: 'Chris',
        lastName: 'Garvie',
        email: 'cgarvie2n@exblog.jp',
        birthDate: '2011-05-30',
        basicSalary: 6219149,
        status: 'Inactive',
        group: 'group 2',
        description: '1958-10-04',
    },
    {
        username: 'rrodliff2o',
        firstName: 'Romeo',
        lastName: 'Rodliff',
        email: 'rrodliff2o@list-manage.com',
        birthDate: '1946-05-14',
        basicSalary: 970182,
        status: 'Active',
        group: 'group 5',
        description: '1991-11-11',
    },
    {
        username: 'lwimlett2p',
        firstName: 'Luelle',
        lastName: 'Wimlett',
        email: 'lwimlett2p@tripod.com',
        birthDate: '1915-02-23',
        basicSalary: 1237444,
        status: 'Active',
        group: 'group 2',
        description: '1956-05-27',
    },
    {
        username: 'kcoopman2q',
        firstName: 'Kent',
        lastName: 'Coopman',
        email: 'kcoopman2q@hao123.com',
        birthDate: '1927-02-04',
        basicSalary: 8608490,
        status: 'Inactive',
        group: 'group 5',
        description: '2012-06-27',
    },
    {
        username: 'asheron2r',
        firstName: 'Ash',
        lastName: 'Sheron',
        email: 'asheron2r@wix.com',
        birthDate: '1902-06-27',
        basicSalary: 6908584,
        status: 'Inactive',
        group: 'group 1',
        description: '1935-03-03',
    },
];
